# Generated by Django 4.2.26 on 2025-11-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_client_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='registration_status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Подтверждён'), ('rejected', 'Отклонён')], default='approved', help_text='Статус регистрации клиента', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram username клиента', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='access_code',
            field=models.CharField(blank=True, help_text='Код доступа для авторизации в боте', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='access_code_created',
            field=models.DateTimeField(blank=True, help_text='Время создания кода доступа', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram chat id водителя', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='telegram_verified',
            field=models.BooleanField(default=False, help_text='Водитель верифицирован в Telegram'),
        ),
    ]
